BOXSCORE_KEY = "Boxscore flex flex-column"
TEAM_NAME = "BoxscoreItem__TeamName h5"
TEAM_TAB = "ResponsiveTable ResponsiveTable--fixed-left Boxscore flex flex-column"
TABLE_BODY = "Table__TBODY"
TABLE_CONTENT = "Table__TR Table__TR--sm Table__even"
PLAYER = "Table Table--align-right Table--fixed Table--fixed-left"
PLAYER_NAME = "AnchorLink truncate db external Boxscore__AthleteName"
PLAYER_POSITION = "playerPosition pl2"
